export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_SIDEBAR_SUCCEEDED = 'TOGGLE_SIDEBAR_SUCCEEDED';
export const TOGGLE_SIDEBAR_FAILED = 'TOGGLE_SIDEBAR_FAILED';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCEEDED = 'GET_JOBS_SUCCEEDED';
export const GET_JOBS_FAILED = 'GET_JOBS_FAILED';